# -*- coding: utf-8 -*-
# Date       : 2023/4/3
# Author     : @ Yi Huang @ Xin Cheng
# email      :
# Description: Solution Refiner Refine the results generated by the Math Resolver

from typing import Dict
from math_ai.codebase.engine.llm import OpenAILLM
from math_ai.codebase.prompt import solution_refiner


class SolutionRefiner:
    def __init__(self):
        self.llm = OpenAILLM()
        self.role = "你是一个数学大师"
        self.llm.set_role(self.role)
        
    def run(self, problem_dict, strategy_dict, first_solution) -> str:
        type_decompose = "多个问题" if strategy_dict["if_muti"] == "muti" else "simple"
        answer = self.llm.llm_response(problem_desc=problem_dict["description"],type_decompose=type_decompose,type_problem=problem_dict["type"],trajectory=first_solution)
        return answer


